site_name: Headbreaker
site_url: https://flbulgarelli.github.io/headbreaker
nav:
  - Home: index.md
repo_url: "https://github.com/flbulgarelli/headbreaker"
copyright: 'Â© Copyright 2020 - 2026 Franco Leonardo Bulgarelli'
docs_dir: docs
